# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-09-11 00:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Srs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vocab', models.CharField(max_length=200)),
                ('pronunciation', models.CharField(max_length=200)),
                ('meaning', models.CharField(max_length=200)),
                ('first_date', models.DateTimeField(verbose_name='date found')),
                ('frequency', models.IntegerField(max_length=10)),
            ],
        ),
    ]
