# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-09-11 00:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='srs',
            name='frequency',
            field=models.IntegerField(),
        ),
    ]
