# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-09-11 02:05
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('subs', '0002_auto_20160911_0027'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='srs',
            name='first_date',
        ),
        migrations.AddField(
            model_name='srs',
            name='owner',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='srs',
            name='meaning',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='srs',
            name='pronunciation',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='srs',
            name='vocab',
            field=models.CharField(max_length=20),
        ),
    ]
