# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-09-12 08:29
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('subs', '0003_auto_20160911_0205'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='srs',
            name='frequency',
        ),
        migrations.AddField(
            model_name='srs',
            name='pos',
            field=models.CharField(default=datetime.datetime(2016, 9, 12, 8, 29, 8, 311655, tzinfo=utc), max_length=40),
            preserve_default=False,
        ),
    ]
